apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mongo-persistentvolumeclaim
    namespace: k8s-template
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 2Gi
