apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: ingress
    namespace: {{.Values.namespace}}
spec:
    rules:
        - host: {{.Values.ingress.adminHost}}
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: mongo-express-service
                            port:
                                number: 8081
        - host: {{.Values.ingress.appHost}}
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: client-service
                            port:
                                number: 8080
                  - path: /api
                    pathType: Prefix
                    backend:
                        service:
                            name: server-service
                            port:
                                number: 8080
