apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: persistentvolumeclaim
    namespace: {{.Values.namespace}}
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: {{.Values.pvcSize}}
