apiVersion: v1
kind: Secret
metadata:
    name: secret
    namespace: {{.Values.namespace}}
type: Opaque
data:
    mongo-root-username: {{.Values.mongoRootUsername | b64enc | quote}}
    mongo-root-password: {{.Values.mongoRootPassword | b64enc | quote}}
